Es6 modules #PR
Sonikak004/ES6-Awesome_Books pull request #1
Opened 2023-05-08 17:12 UTC by Sonikak004

### In this Branch I have: 👍 

- Used **ES6** syntax. ✅ 
- Divide code into **modules**.  
- Created a separate file for each module in the **modules directory**. 
- Refactored all functions to **arrow functions**.  ✅ 
- used **Luxon** Library.
- Fix all **Linter** errors. ✔️

2023-05-08 17:20 UTC, Shisui6 reviewed
Hi @Sonikak004, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a project, that doesn't have a professional readme file. Please make sure to use the microverse [template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-08 17:22 UTC, Shisui6 reviewed
null

2023-05-08 18:19 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Sonikak004  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 18:19 UTC, iambenkis commented on Modules/book.js
> +}
Good job creating this module , I like the way to use make your modules  , also it could be better to   use `arrow` syntax for functions. Using `class` is a way to do it , however to meet the requirements 👍 Kindly use the `arrow` functions.

```bash
const Book = () => {
// ... put your code here
}
```

2023-05-08 18:19 UTC, iambenkis commented on Modules/store.js
> +}
Also, here ,  it could be better to   use `arrow` syntax for functions. Using `class` is a way to do it , however to meet the requirements 👍 Kindly use the `arrow` functions.

```bash
const getBook = () => {
// Put your code here
}
```
I suggest also to put the other function in a new module and it will result in something like this 👎 

```bash
const addBook = () => {
// Put your code here
}
```

2023-05-08 18:19 UTC, iambenkis commented on Modules/ui.js
> +  }
Kindly prioritize the use of `arrow` function instead of `class` specifically for this milestone 😄

2023-05-08 18:19 UTC, iambenkis commented on index.js
> +  document.getElementById('date-time').innerHTML = `${formattedDateTime}`;
You did a great job by creating the dateAndTime function  but I noticed that the current date is not displayed below the navigation bar, for this requirement, you **should** use the [Luxon](https://github.com/moment/luxon/blob/master/docs/install.md) library. See [Get the current date and time](https://github.com/moment/luxon/blob/master/docs/tour.md#get-the-current-date-and-time). Kindly fix that

2023-05-08 18:19 UTC, iambenkis commented on index.js
> +const contactSection = document.getElementById('contact-section');
The navigation bar is not working as it should , reason why I do not have the possibility to check that , Kindly fix the navigation bar and make sure the `addBook` and the `removeBook` functions are working 👍

2023-05-09 04:21 UTC, Davidosky007 approved these changes
Hi @Sonikak004 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* ES6 syntax used properly 👍 
* No linter errors 👍 
* Well written PR 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 04:33 UTC, merged